@startuml
  :Inicio a rotina;
  :Conecta com base; 
  :Busca todos os itens cadastrados;
  :Efetua a leitura na pasta retornando todos os itens;
  if(O Livro da pasta esta base?) then (yes)
    if(o status de Leitura foi efetuado?)then(yes)
      :Deleta livro local;
    endif
  else (no)
    :Cadastrar livro na base \r com leitura nao efetuada;
  endif
  :Verifica a quantidade de livros cadastrados \r com staus de leitura nao efetuado;
  :E gera um valor randomico com essa quantidade e \r e verifica qual livro corresponde ao valor.;
  :Mandar email com livro escolhido em anexo;
  :Atualizar o status de leitura da base;
  :Deleta o livro local;
  :Encerra o rotina com sucesso;
  stop
  
@enduml