version: '3.0'

services:

  localstack:
    image: localstack/localstack:latest
    environment: 
      - EDGE_PORT=4566
      - SERVICES=dynamodb
      - KINESIS_PROVIDER=kinesalite
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=sa-east-1
    ports:
      - '4566:4566'
    volumes:
      - '/var/folders/5h/s7tly89s3sv316634kx_2nvr0000gn/T/:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
