name: Deploy Testes AWS DocumentDB with Terraform and Node.js

on:
  push:
    branches:
      - repoMongoteste

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print AWS Credentials
        run: |
          echo "AWS Access Key ID: ${{ secrets.AWS_ACCESS_TESTE_USER }}"
          echo "AWS Secret Access Key: ${{ secrets.AWS_ACCESS_TESTE_PASS }}"
